version: '3.6'
services:
  server:
    hostname: server
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    
    ports: 
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/opt/irisapp
      
  client:
    hostname: client
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    
    ports: 
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/opt/irisapp
